config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: %i[show]
  resources :flats, only: %i[show new create edit update destroy]

  resources :bookings, only: %i[show create destroy] do
    resources :reviews, only: %i[new create destroy]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to user_path(@booking.user), notice: 'Booking was successfully created.'
    else
      @flat = @booking.flat
      render 'flats/show'
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flat= @booking.flat
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.destroy
      redirect_to user_path(current_user), notice: 'Booking has been canceled successfully! :D'
    else
      redirect_to booking_path(@booking), alert: 'Failed to cancel your booking.'
    end
  end
  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :flat_id)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def show
    @flat = Flat.find(params[:id])
    @booking = Booking.new
    @reviews = Review.joins(booking: :flat).where(bookings: { flat_id: params[:id] })
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @flats = Flat.all
    if params[:query].present?
      sql_subquery = <<~SQL
        flats.name @@ :query
        OR flats.address @@ :query
      SQL
      @flats = @flats.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking_id = Booking.find(params[:booking_id]).id
    if @review.save
      redirect_to flat_path(@review.booking.flat), notice: 'Review was successfully registered.'
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating, :booking_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @bookings = Booking.where(user: current_user)
    @upcoming_bookings = @bookings.where("start_date > ?", Date.today)
    @past_bookings = @bookings.where("start_date < ?", Date.today)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<%# <h1>As a user I can delete a booking</h1> %>
<%# <h1>As a user I can leave a review</h1> %>
<div class="show-container p-4 m-4">
  <h1><%= @flat.name %></h1>
  <div class="d-flex justify-content-between align-self-start rounded p-4" style="background-color:white; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
    <div class="flat-img-container" style="height:200px">
      <img src="<%= @flat.photos %>" class="h-100" style="object-fit: cover;" alt="flat_photo">
    </div>
    <div class="flat-info-container flex-grow-1 d-flex flex-column px-4">
      <h6>Date</h6>
      <p class="text-dark"><%= @booking.start_date.strftime('%Y-%m-%d') %> ~ <%= @booking.end_date.strftime('%Y-%m-%d') %></p>
    </div>
    <% if @booking.start_date.to_date > Date.today %>
      <div class="booking-cancel">
        <%= button_to  booking_path(@booking), method: :delete, data: { confirm: 'Are you sure you want to remove this exercise?' }, class:"btn btn-danger border rounded-5"  do %>
          <p class="mb-0 text-white">cancel <i class="fa-solid fa-x" style="color: #ffffff;"></i></p>
        <% end %>
      </div>
    <% else %>
      <div class="booking-review">
        <%= link_to new_booking_review_path(@booking), class:"btn btn-dark border rounded-5" do %>
          <p class="mb-0">Leave a review</p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/edit.html.erb
<h1>As a owner I can edit a flat</h1>

app/views/flats/new.html.erb
<h1>As a owner I can create a flat</h1>

app/views/flats/show.html.erb
<%# <h1>As a user I can see one flat</h1> %>
<div class="show-container p-4 m-4">
  <h1><%= @flat.name %></h1>
  <div class="d-flex justify-content-between rounded p-4" style="height:500px; background-color:white; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
    <div class="flat-img-container flex-grow-1" style="height:100%">
      <img src="<%= @flat.photos %>" class="w-100 h-100" style="object-fit: cover;" alt="flat_photo">
    </div>
    <div class="flat-info-container d-flex flex-column px-4">
      <%= @flat.description %>
      <div class="d-flex align-items-center justify-content-start">
        <i class="fa-solid fa-user-group card-subtext-icon" style="margin-bottom:0px; margin-right:8px"></i>
        <p class="card-subtext" style="margin-bottom:0px; margin-right:8px"><%= @flat.limit_guests %></p>
        <i class="fa-solid fa-euro-sign card-subtext-icon" style="margin-bottom:0px; margin-right:8px"></i>
        <p class="card-subtext" style="margin-bottom:0px; margin-right:8px"><%= @flat.price %></p>
      </div>
      <div class="book-flat-form mt-auto p-4 rounded" style="box-shadow: 0 0 15px rgba(0,0,0,0.2);">
        <%= simple_form_for @booking, url: bookings_path do |f| %>
          <%= f.hidden_field :flat_id, value: @flat.id %>
          <div class="form-group">
            <%= f.input :start_date, as: :date, label: "Start Date", input_html: { class: "form-control" } %>
          </div>
          <div class="form-group">
            <%= f.input :end_date, as: :date, label: "End Date", input_html: { class: "form-control" } %>
          </div>
          <div class="form-group">
            <%= f.button :submit, "Submit", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%# <h2>As a user I can see reviews of the flat</h2> %>
<div class="reviews-container p-5">
  <h1>Reviews</h1>
  <% @reviews.each do |review| %>
    <div class="review-container py-3 px-5 mb-3" style="background-color:white">
      <p>
        <% review.rating.times do %>
          <i class="fa-solid fa-star"></i>
        <% end %>
        <% (5 - review.rating).times do %>
          <i class="fa-regular fa-star"></i>
        <% end %>
      </p>
      <p><%= review.comment %></p>
      <p class="text-end mb-0">by <em><%= review.booking.user.name %></em></p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbDemo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-white shadow-sm">
      <div class="container-fluid mx-3 d-flex align-items-center">
        <%= link_to root_path, class: 'navbar-brand navbar-dark d-flex align-items-center' do %>
          <i class="fa-solid fa-house-flag" style="color: #e68619; margin-right: 8px;"></i>
          <span class="fs-3 fw-bold mb-0 text-dark">RetroBnB</span>
        <% end %>

        <div class="navbar-right">
          <% if user_signed_in? %>
            <%= link_to 'Profile', user_path(current_user), class: 'btn btn-dark rounded-5' %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <h1>Discover Your Perfect Vintage Home</strong>!</h1>
    <p>Experience the charm and elegance of a bygone era with our curated selection of vintage houses.</p>
    <div class="row justify-content-start">
      <div class="col-sm-8 my-3">
        <%= form_with url: root_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Type a keyword"
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-primary ms-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container mt-5">
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4 d-flex">
        <%= link_to flat_path(flat), class:"text-decoration-none" do %>
          <div class="card flex-fill">
            <img src="<%= flat.photos %>" class="card-img-top" alt="flat_photo">
            <div class="card-body d-flex flex-column">
              <h5 class="card-title"><%= flat.name %></h5>
              <p class="card-text"><%= flat.address %></p>
              <div class="subtext-box mt-auto d-flex align-items-center justify-content-end">
                <i class="fa-solid fa-user-group card-subtext-icon" style="margin-bottom:0px; margin-right:8px"></i>
                <p class="card-subtext" style="margin-bottom:0px; margin-right:8px"><%= flat.limit_guests %></p>
                <i class="fa-solid fa-euro-sign card-subtext-icon" style="margin-bottom:0px; margin-right:8px"></i>
                <p class="card-subtext" style="margin-bottom:0px; margin-right:8px"><%= flat.price %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="book-flat-form mt-auto p-4 rounded" style="width:70%; margin:0 auto; background-color:white; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
  <%= simple_form_for [@booking, @review], url: booking_reviews_path do |f| %>
    <%= f.hidden_field :booking_id, value: @booking %>
    <div class="form-group">
      <%= f.input :comment, as: :text, label: "Comment", placeholder: "Such a lovely meal!", input_html: { class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= f.input :rating, label: "Rating", collection: 1..5, include_blank: false %>
    </div>
    <div class="form-group">
      <%= f.button :submit, "Submit Review", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="dashboard-container d-flex w-75 mt-3 " style="margin:0 auto; background-color:white">
  <div class="profile-container d-flex flex-column align-items-center p-3 m-5 rounded-5" style="width:350px; height:200px; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
    <div class="border rounded-circle d-flex align-items-center justify-content-center" style="width:100px; height:100px">
      <i class="fa-solid fa-user" style="font-size: 4rem;"></i>
    </div>
    <%= current_user.name %>
    <% if current_user.owner_mode %>
      <p>Host</p>
      <i class="fa-solid fa-toggle-on"></i>
    <% else %>
      <p>Traveller</p>
      <i class="fa-solid fa-toggle-on fa-flip-horizontal"></i>
    <% end %>
  </div>
  <div class="bookings-container d-flex flex-column flex-grow-1">
    <div class="my-bookings-container m-5 mb-3 d-flex flex-column ">
      <h3 class="mb-3">Upcoming bookings</h3>
      <% @upcoming_bookings.each do |booking| %>
        <%= link_to booking_path(booking), class:"text-decoration-none" do %>
          <div class="my-booking-card">
            <img src="<%= booking.flat.photos %>" class="" alt="flat_photo">
            <div class="my-booking-infos d-flex justify-content-between flex-grow-1">
              <div>
                <h5 class="text-dark"><%= booking.flat.name %></h5>
                <p class="text-dark"><%= booking.start_date.strftime('%Y-%m-%d') %> ~ <%= booking.end_date.strftime('%Y-%m-%d') %></p>
              </div>
              <p class="booking-status d-flex align-items-center justify-content-center mt-0 text-dark">
                <% if booking.confirm %>
                  Confirmed
                <% else %>
                  Pending
                <% end %>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="my-bookings-container m-5 mt-0 d-flex flex-column">
      <h3 class="mb-3">Past bookings</h3>
      <% @past_bookings.each do |booking| %>
        <%= link_to booking_path(booking), class:"text-decoration-none" do %>
          <div class="my-booking-card">
            <img src="<%= booking.flat.photos %>" class="" alt="flat_photo">
            <div class="my-booking-infos d-flex justify-content-between flex-grow-1">
              <div>
                <h5 class="text-dark"><%= booking.flat.name %></h5>
                <p class="text-dark"><%= booking.start_date.strftime('%Y-%m-%d') %> ~ <%= booking.end_date.strftime('%Y-%m-%d') %></p>
              </div>
              <p class="booking-status d-flex align-items-center justify-content-center mt-0 text-dark">
                <% if booking.confirm %>
                  Confirmed
                <% else %>
                  Pending
                <% end %>
              </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>